name = "holo-router-registry"
type = "webpack"
account_id = "18ff2b4e6205b938652998cfca0d8cff"
zone_id = "35f34e8f9d04ef8c87283ea9fb812989"
route = "router-registry.holo.host/*"

[[kv-namespaces]]
binding = "AGENT_ID_TO_IPV4"
id = "e3de244cdc5241ce8b68096a3fab78ff"

[[kv-namespaces]]
binding = "SETTINGS"
id = "7ac3842e281a4202a6f8279d0c54435e"
