repository:
  name: router-registry
  description: Cloudflare Worker that stores [hcid, zt-IP] pairs for router's DNS
  topics: holo, holochain, cloudflare-worker
  private: true
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: develop
  allow_merge_commit: true
  allow_squash_merge: false
  allow_rebase_merge: false

collaborators: []

teams:
  - name: holo-hosting
    permission: push

branches:
  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      restrictions:
        users: []
        teams:
          - holo-hosting

  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: false

        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions:
        users: []
        teams:
          - holo-hosting
