[package]
name = "holo-router-gateway"
edition = "2018"
version = "0.0.0"

[dependencies]
env_logger = "0.7.1"
failure = "0.1.6"
futures = "0.3"
log = "0.4.8"
nix = "0.16.1"
rustls = "0.16.0"
tokio = { version = "0.2.8", features = ["full"] }
uuid = { version = "0.8.1", features = ["v4"] }
